version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fastapi_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network
    restart: unless-stopped

  fastapi-app:
    build: ./app
    container_name: fastapi_app
    expose:
      - "8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi-app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
